project_id = "fp_ecosystem"

[api]
schemas = [
  "public",
  "graphql_public",
  "core",
  "robots",
  "food",
  "gateway",
  "tracking",
  "marketing",
  "sales",
  "tickets",
  "billing"
]
extra_search_path = ["public", "extensions"]
max_rows = 1000
